version: '3'

services:

  calculator_ws:
    image: quay.io/l2x6/calculator-ws:1.0
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: "gvenzl/oracle-xe"
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=oracle
    ports:
      - "1521:1521"
    volumes:
      - oracledb_data:/opt/oracle/oradata
    depends_on:
      - calculator_ws
    healthcheck:
      test: "sqlplus sys/oracle@//localhost:1521/ORCLCDB as sysdba && echo 'select 1 from dual;' | sqlplus sys/oracle@//localhost:1521/ORCLCDB as sysdba"
      interval: 30s
      timeout: 20s
      retries: 10

volumes:
  oracledb_data:
