
package com.restapi.employeeapi.dto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorService", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "org.jboss.eap.quickstarts.wscalculator.calculator.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "org.jboss.eap.quickstarts.wscalculator.calculator.DivideResponse")
    public int divide(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "org.jboss.eap.quickstarts.wscalculator.calculator.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "org.jboss.eap.quickstarts.wscalculator.calculator.AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "org.jboss.eap.quickstarts.wscalculator.calculator.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "org.jboss.eap.quickstarts.wscalculator.calculator.SubtractResponse")
    public int subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.jboss.eap.quickstarts.wscalculator.calculator.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addOperands", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "org.jboss.eap.quickstarts.wscalculator.calculator.AddOperands")
    @ResponseWrapper(localName = "addOperandsResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "org.jboss.eap.quickstarts.wscalculator.calculator.AddOperandsResponse")
    public Result addOperands(
        @WebParam(name = "arg0", targetNamespace = "")
        Operands arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "org.jboss.eap.quickstarts.wscalculator.calculator.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "org.jboss.eap.quickstarts.wscalculator.calculator.MultiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
